name: CI build
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - "**"
  repository_dispatch:
    types: build_application
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: Check out and publish
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: devsrev
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      FROMADDRESS: ${{ secrets.FROMADDRESS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |-
          npm ci
          npm test
          time node backend.js
          git config --global user.name 'Sven Anders Robbestad'
          git config --global user.email 'robbestad@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add build/taken.json
          git add build/meta.json
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            cd frontend
            npm i
            npm run build
            cp ../build/*.json build
            git commit -m"updated json files"
            git push origin main
            npx gulp github
            cd publish
            npm install -g surge
            surge ./ --token ${{ secrets.SURGE_TOKEN }}
          else
            echo "Not publishing as no files were changed"
          fi
