name: CI build
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  repository_dispatch:
    types: build_application
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    name: Check out and publish
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: devsrev
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      FROMADDRESS: ${{ secrets.FROMADDRESS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |-
          npm ci
          npm test
          time node backend.js
          #sleep 10
          echo "---- ls"
          ls
          echo "---- ls build"
          ls build
          mv build/taken2.json build/taken.json
          git add build/taken.json
          git commit -m"updated taken.json"
          git push origin main
          npx gulp github
          cd publish
          ls
          npm install -g surge
          surge ./ --token ${{ secrets.SURGE_TOKEN }}
