name: CI build
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  repository_dispatch:
    types: build_application
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    name: Check out and publish
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: devsrev
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      FROMADDRESS: ${{ secrets.FROMADDRESS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          npm ci
          npm test
          node backend.js
          sleep 10
          npx gulp github
          ls
          ls build
          mv build/token2.json build/token.json
          git add token.json
          git commit -m"updated token.json"
          git push origin main
          cd publish
          ls
          npm install -g surge
          surge ./ --token ${{ secrets.SURGE_TOKEN }}
