name: Publish to surge
on:
  workflow_dispatch:
  repository_dispatch:
    types: publish_application

jobs:
  build:
    name: Check out and publish
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: devsrev
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      FROMADDRESS: ${{ secrets.FROMADDRESS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to devsrev.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "devsrev.surge.sh"
          project: "./publish"
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
