name: CI Build w/Svelte
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  repository_dispatch:
    types: build_frontend
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: Check out and publish
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: devsrev
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      FROMADDRESS: ${{ secrets.FROMADDRESS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |-
          npm ci
          npm test
          time node backend.js
          git config --global user.name 'Sven Anders Robbestad'
          git config --global user.email 'robbestad@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add build/*.json
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            cd frontend
            npm ci
            npm run build
            cp ../build/*.json public
            git add public
            git commit -m"updated svelte front"
            git push origin main
            npx gulp github
            npm install -g surge
            cp CNAME publish
            cd publish
            surge ./ --token ${{ secrets.SURGE_TOKEN }}
          else
            echo "no changes"
            cd frontend
            npm ci
            npm run build
            cp ../build/*.json public
            git add public
            git commit -m"updated svelte front"
            git push origin main
            npx gulp github
            npm install -g surge
            cp CNAME publish
            cd publish
            surge ./ --token ${{ secrets.SURGE_TOKEN }}
          fi
